schema:
  name: dbo
server:
  port: ${PORT:8080}
spring:
  messages:
    basename: bundles/messages
    encoding: UTF-8
    cache-duration: -1
    fallback-to-system-local: false
    use-code-as-default-message: true
  jpa:
    properties:
      hibernate:
        default_schema: ${schema.name}
        ddl-auto: none
        generate-ddl: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db
    schemas: ${schema.name}
    placeholders:
      id_type: serial