schema:
  name: dbo
server:
  port: ${PORT:8080}
spring:
  messages:
    basename: bundles/messages
    encoding: UTF-8
    cache-duration: -1
    fallback-to-system-local: false
    use-code-as-default-message: true
  jpa:
    properties:
      hibernate:
        default_schema: ${schema.name}
        ddl-auto: none
        generate-ddl: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db
    schemas: ${schema.name}
    placeholders:
      id_type: serial
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${googleClientId}
            client-secret: ${googleClientSecret}
            redirect-uri: "{baseUrl}/api/v1/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: "profile"
          discord:
            client-id: ${discordClientId}
            client-secret: ${discordClientSecret}
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope:
              - identify
            redirect-uri: "{baseUrl}/api/v1/login/oauth2/code/discord"
            client-name: GlacierFrost2Builds
        provider:
          discord:
            authorization-uri: https://discordapp.com/api/oauth2/authorize
            token-uri: https://discordapp.com/api/oauth2/token
            user-info-uri: https://discordapp.com/api/users/@me
            username-attribute: username